name: Document Publish
on:
  push:
    branches:
      - main
jobs:
  document-publish:
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]'
    steps:
      - name: Checkout 🔔
        uses: actions/checkout@v4
      - name: Node Setup 🔔
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'
      - name: Link 🔨
        run: yarn
      - name: packages build 🔨
        run: yarn build
      - name: prepare 🔨
        run: yarn prepare:docs
      - name: document build 🔨
        run: yarn build:docs
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.PUBLISH_TOKEN }}
          folder: ./docs/build
