name: pull request test
on:
  pull_request:
    branches:
      - master
jobs:
  pull-request-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🔔
        uses: actions/checkout@v3
      - name: Node Setup 🔔
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'
      - name: install 🔨
        run: yarn
      - name: typecheck 🚀
        run: yarn typecheck
      - name: testing 🚀
        run: yarn test