name: Pull Request
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
jobs:
  Build-Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🔔
        uses: actions/checkout@v4
      - run: corepack enable
      - name: Node Setup 🔔
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'
      - name: install 🔨
        run: yarn install --immutable
      - name: build 🔨
        run: lerna run build
      - name: eslint 🚀
        run: yarn eslint packages
      - name: typecheck 🚀
        run: yarn typecheck
      - name: testing 🚀
        run: yarn test
      - name: document prepare 🔨
        run: yarn prepare:docs
        if: github.event.pull_request.user.login == 'dependabot[bot]'
      - name: document build 🔨
        run: yarn build:docs
        if: github.event.pull_request.user.login == 'dependabot[bot]'