name: Release
on:
  push:
    branches:
      - main
jobs:
  packages-release:
    runs-on: ubuntu-latest
    steps:
      - run: corepack enable
      - name: Checkout 🔔
        uses: actions/checkout@v4
      - name: Node Setup 🔔
        uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'
      - name: install 🔨
        run: yarn install
      - name: build 🔨
        run: lerna run build
      - name: typecheck 🚀
        run: yarn typecheck
      - name: testing 🚀
        run: yarn test
      - name: Create Release Pull Request or Publish to npm
        uses: changesets/action@v1
        with:
          title: 'chore: version packages'
          commit: 'chore: version packages'
          version: yarn changeset:version
          publish: yarn changeset:publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
